server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name app.opside.code-talent.fr;

    ssl_certificate /etc/letsencrypt/live/app.opside.code-talent.fr/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/app.opside.code-talent.fr/privkey.pem;

    location / {
        proxy_pass http://127.0.0.1:3102;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name api-app.opside.code-talent.fr;

    ssl_certificate /etc/letsencrypt/live/api-app.opside.code-talent.fr/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api-app.opside.code-talent.fr/privkey.pem;

    location / {
        proxy_pass http://127.0.0.1:3101;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
    }
}

server {
    listen 80;
    listen [::]:80;
    server_name app.opside.code-talent.fr api-app.opside.code-talent.fr;
    return 301 https://$host$request_uri;
}
