module.exports = {
  apps: [
    {
      name: 'opside-app-backend',
      cwd: '/home/ubuntu/OPSIDE_Project/backend',
      script: 'dist/src/main.js',
      interpreter: '/home/ubuntu/.local/bin/node22',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      min_uptime: '20s',
      max_restarts: 20,
      restart_delay: 4000,
      exp_backoff_restart_delay: 200,
      max_memory_restart: '700M',
      kill_timeout: 8000,
      out_file: '/home/ubuntu/.pm2/logs/opside-app-backend-out.log',
      error_file: '/home/ubuntu/.pm2/logs/opside-app-backend-error.log',
      merge_logs: true,
      time: true,
      env_file: '/home/ubuntu/OPSIDE_Project/backend/.env.production',
      env: {
        NODE_ENV: 'production',
        PORT: '3101',
      },
    },
    {
      name: 'opside-app-frontend',
      cwd: '/home/ubuntu/OPSIDE_Project/frontend',
      script: 'npm',
      args: 'run start -- -H 127.0.0.1 -p 3102',
      interpreter: '/usr/bin/node',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      min_uptime: '20s',
      max_restarts: 20,
      restart_delay: 4000,
      exp_backoff_restart_delay: 200,
      max_memory_restart: '900M',
      kill_timeout: 8000,
      out_file: '/home/ubuntu/.pm2/logs/opside-app-frontend-out.log',
      error_file: '/home/ubuntu/.pm2/logs/opside-app-frontend-error.log',
      merge_logs: true,
      time: true,
      env_file: '/home/ubuntu/OPSIDE_Project/frontend/.env.production',
      env: {
        NODE_ENV: 'production',
      },
    },
    {
      name: 'opside-watchdog',
      cwd: '/home/ubuntu/OPSIDE_Project',
      script: '/home/ubuntu/OPSIDE_Project/deploy/opside-watchdog.js',
      interpreter: '/usr/bin/node',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      min_uptime: '10s',
      max_restarts: 50,
      restart_delay: 5000,
      exp_backoff_restart_delay: 200,
      max_memory_restart: '250M',
      out_file: '/home/ubuntu/.pm2/logs/opside-watchdog-out.log',
      error_file: '/home/ubuntu/.pm2/logs/opside-watchdog-error.log',
      merge_logs: true,
      time: true,
      env: {
        OPSIDE_BACKEND_PORT: '3101',
        OPSIDE_FRONTEND_PORT: '3102',
        OPSIDE_BACKEND_PM2_NAME: 'opside-app-backend',
        OPSIDE_FRONTEND_PM2_NAME: 'opside-app-frontend',
        OPSIDE_BACKEND_MEM_MB_LIMIT: '850',
        OPSIDE_FRONTEND_MEM_MB_LIMIT: '1050',
      },
    },
  ],
};
