INSERT INTO "Skill" (name, category)
VALUES 
    ('React', 'frontend'),
    ('Vue.js', 'frontend'),
    ('Angular', 'frontend'),
    ('Next.js', 'frontend'),
    ('TypeScript', 'frontend'),
    ('HTML/CSS', 'frontend'),
    ('Tailwind', 'frontend'),
    ('Node.js', 'backend'),
    ('NestJS', 'backend'),
    ('Python', 'backend'),
    ('Django', 'backend'),
    ('FastAPI', 'backend'),
    ('PHP', 'backend'),
    ('Laravel', 'backend'),
    ('Java', 'backend'),
    ('Spring Boot', 'backend'),
    ('React Native', 'mobile'),
    ('Flutter', 'mobile'),
    ('Swift', 'mobile'),
    ('Kotlin', 'mobile'),
    ('Docker', 'devops'),
    ('Kubernetes', 'devops'),
    ('AWS', 'devops'),
    ('CI/CD', 'devops'),
    ('Terraform', 'devops'),
    ('PostgreSQL', 'data'),
    ('MongoDB', 'data'),
    ('Redis', 'data'),
    ('Elasticsearch', 'data'),
    ('Python Data', 'data'),
    ('SQL', 'data'),
    ('Figma', 'design'),
    ('Photoshop', 'design'),
    ('AdobeXD', 'design'),
    ('Photopea', 'design')
ON CONFLICT (name) DO NOTHING;